<table id="matChart" class="mChart">
    <tr>
        <th>Alum.<br/>Alloy</th>
        <th>Carb.<br/>Steel</th>
        <th>Alloy Steel</th>
        <th>Hard.<br/>Steel</th>
        <th>Nickel<br/>Alloy</th>
        <th>Stain.<br/>Steel</th>
        <th>Cast<br/>Iron</th>
        <th>Tit.</th>
    </tr>
    <tr>
        <td><div id="matAL"></div></td>
        <td><div id="matCS"></div></td>
        <td><div id="matAS"></div></td>
        <td><div id="matHS"></div></td>
        <td><div id="matNI"></div></td>
        <td><div id="matSS"></div></td>
        <td><div id="matCI"></div></td>
        <td><div id="matTI"></div></td>
    </tr>
    <tr><td colspan="8"><hr/></td></tr>
    <tr class="legandSize"><td colSpan="4"><div class="bestDot legandTxt"></div><div class="legandTxt">&nbsp;&nbsp; Best Use of Product</div></td><td colSpan="4" ><div class="goodDot legandTxt"></div><div class=" legandTxt">&nbsp;&nbsp; Good Use of Product</div></td></tr>
</table>