<?php
/**
 * Magento
 *
 */

/**
 * Product media data template
 *
 * @see Mage_Catalog_Block_Product_View_Media
 */
?>
<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
?>
<?php  
if($_product->getImage()){
	print_r('<div id="mainImage"><img src="'.$this->helper('catalog/image')->init($_product,'image').'"/></div>');
}
?>
<!-- 
<?php //if ($_product->getImage() != 'no_selection' && $_product->getImage()): ?>
<p class="product-image product-image-zoom">
    <?php
        //$_img = '<img id="image" src="'.$this->helper('catalog/image')->init($_product, 'image').'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
        //echo $_helper->productAttribute($_product, $_img, 'image');
        
    ?>
</p>

<p class="zoom-notice" id="track_hint"><?php //echo $this->__('Double click on above image to view full picture') ?></p>
<div class="zoom">
    <img id="zoom_out" src="<?php //echo $this->getSkinUrl('images/slider_btn_zoom_out.gif') ?>" alt="<?php //echo $this->__('Zoom Out') ?>" title="<?php //echo $this->__('Zoom Out') ?>" class="btn-zoom-out" />
    <div id="track">
        <div id="handle"></div>
    </div>
    <img id="zoom_in" src="<?php //echo $this->getSkinUrl('images/slider_btn_zoom_in.gif') ?>" alt="<?php //echo $this->__('Zoom In') ?>" title="<?php //echo $this->__('Zoom In') ?>" class="btn-zoom-in" />
</div>
<script type="text/javascript">
//<![CDATA[
//    Event.observe(window, 'load', function() {
//        product_zoom = new Product.Zoom('image', 'track', 'handle', 'zoom_in', 'zoom_out', 'track_hint');
//    });
//]]>
</script>
 -->