
<?php
if($_GET['qRec']): 
$solrPg=Mage::helper('solr')->bURL();
echo('<input type="hidden" id="tt" name="tt" value="'.$_GET['qRec'].'" />');
?>
 <script type="text/javascript">
 jQuery(document).ready(function ($){
	 
		if($('#tt').val() && $('#tt').val() != 'sGo' && $('#bodySearch').val()==""){
			var bsState=$('#tt').val();
			$.removeCookie('KTS_CC1');
			$.removeCookie('KTS_ALD');
			$.post('<?php echo($solrPg); ?>solr/index/index/',{qRec:$('#tt').val()}, function(data){ $('#solrBurn').html(data); },'html'); //qRec
			$('#search').val($('#tt').val());
			$('#bodySearch').val($('#tt').val());
			$('#search').focus(function(){ $('#search').val(""); });
		}else{
			$('#search').val("Search KensToolSupply.com");
		}
		$('#bodySearch').focus(function(){ $('#bodySearch').val("");});
		$('#body_mini_form').submit(function(event){
			$.removeCookie('KTS_CC1');
			$.removeCookie('KTS_ALD');
			bsState=$('#bodySearch').val();
			bsClean=bsState.replace('"','').replace('"','');
			if($('#pSearch').html()==""){
				$('#pSearch').html(bsClean);
				$.cookie('KTS_PS',bsClean);
			}else{
			var psOut= $('#pSearch').html()+','+bsClean
			$('#pSearch').html(psOut);
			$.cookie('KTS_PS',psOut);
			}
			$.post('<?php echo($solrPg); ?>solr/index/index/',{qRec:$('#bodySearch').val(),ff:'bmf'}, function(data){ $('#solrBurn').html(data); },'html'); //qRec
			$('#bodySearch').val(bsState);
		});		
		$('#bodySearch').autocomplete({ //autocomplete for on page search
			source: function(request,response){ $.getJSON('<?php echo($solrPg); ?>solr/index/index',{sug:request.term},response); }
		});

//Moved from controller --------------------------------------------------------------------------------------------------->>		
	//init fSel
	if(!fSel){
		var fSel = new Array();
		fSel[0]="";fSel[1]="";fSel[2]="";
	}
	
	//init cookies
	if(!$.cookie('KTS_ALD')){
		$.cookie('KTS_ALD','0');
	}
	if($.cookie('KTS_PS')){
		//replace
		$('#pSearch').html($.cookie('KTS_PS'));
	}else{
		//init
		$.cookie('KTS_PS','0');
	}
	if(!$.cookie('KTS_CC1')){
		$.cookie('KTS_CC1',fSel.toString());
	}


  	//on load check cookie for selections
		if($.cookie('KTS_ALD')){
			fSelOnLoad();
		}
		    
		function fSelOnLoad(){
			//read cookies
				var ald = $.cookie('KTS_ALD');
				var fSel1 = $.cookie('KTS_CC1');
				fSel1 = fSel1.split(',');
				fsTemp1 = fSel1[1].split('.');
				fSel1[1]='$'+fsTemp1[0]+'.00'; //cover the money stuffs
				
			//replace filter data on search start only
				if(ald == '0'){
					//get filter data based on main search.
				$.post('<?php echo($solrPg); ?>solr/sub/index/',{term:$('#search').val(),action:'sc',type:'price'}, function(data){ $('#idPrice').html(data); },'html');
				$.post('<?php echo($solrPg); ?>solr/sub/index/',{term:$('#search').val(),action:'sc',type:'manu'}, function(data){ $('#idManufacturer').html(data); },'html');
				$.post('<?php echo($solrPg); ?>solr/sub/index/',{term:$('#search').val(),action:'sc',type:'cata'}, function(data){ $('#idCategory').html(data); },'html');
				}
		}
		
//		$('#narrow-by-list>dt>ol>li').click(function(){
//			alert('fire - 1');
//			});

$('#idPrice').on('click','.priceLI',function(e){
	alert('fire: '+$(this).html());
});



});
 </script>
<div id="solrWrap">
<input type="hidden" id="bodySearch" name="qRec" value="" />
<!--	<form id="body_mini_form" action="#" method="get">
		<div class="body-search">
			<input id="bodySearch" class="input-text" type="text" name="qRec"><button id="goBut" type="submit" class="body-button" />
		</div>
	</form>  -->
	<div id="pSearch"></div>
	<div id="solrBurn"></div>

</div>
<?php else:; ?>
<div>Error.</div>
<?php endif; ?>