
<?php
if($_GET['qRec']):
$url='http://65.60.97.68:8983/solr/KTS1/select?rows=1000&wt=json&q='.urlencode($_REQUEST['qRec']);
$solrPg=Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB);
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, $url);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
$output=curl_exec($ch);
$result=json_decode($output, TRUE);
foreach($result['response']['docs'] as $rOut1){
	$sID[] = $rOut1['sku'];
	$sID1[]=$rOut1['id'];
}
//send prod data to session that is used by local/Mage/catalog/block/Product/List.php to build conditional product collections or filtered collections.
$session = Mage::getSingleton('core/session', array('name'=>'frontend'));

//clear session data on search change
if($session->getData('solrFilter-qRec')!=$_GET['qRec']){
	//nullify p,m,c,oneArr
	$session->setData('solrFilter-price',null);
	$session->setData('solrFilter-man',null);
	$session->setData('solrFilter-cat',null);
	$session->setData('oneArr',null);
}
//set new search param
$session->setData('solrFilter-qRec',$_GET['qRec']);
//set filter base
$session->setData('aFilt',$sID1);
//set collection data
if(!$session->getData('oneArr') || count($session->getData('oneArr'))==count($sID1)){
$session->setData('oneArr',$sID1);
}
//test output:
/*
echo("priceSet: ".$session->getData('solrFilter-price').'<br/>');
echo("manSet: ".$session->getData('solrFilter-man').'<br/>');
echo("catSet: ".$session->getData('solrFilter-cat').'<br/>');
echo("qRec: ".$session->getData('solrFilter-qRec').'<br/>');
echo("oneArr count: ".count($session->getData('oneArr')).'<br/>');
echo("aFilt count: ".count($session->getData('aFilt')));
*/
?>
 <script type="text/javascript">
 jQuery(document).ready(function ($){
	 var nURL = 'http://'+document.URL.split('/')[2];
	$('#search').val('<?php echo($_REQUEST['qRec']) ?>');
	
	$('.priceLI').on('click',function(e){ 
		var sel = $(this).html();
		var base = sel.split(' ');
		var lPrice = base[0].substring(1,base[0].length);
		var hPrice = base[2].substring(1,base[2].length);
		$.post(nURL+'/solr/sub/index/',{'action':'priceClick','lp':lPrice,'hp':hPrice,'sfp':sel},function(data){$('#outTest').html(data); uGoNow();},'html');
	});
	$('#fClrPrice').on('click',function(e){
		$.post(nURL+'/solr/sub/index/',{'action':'priceClr'},function(data){$('#outTest').html(data); uGoNow();},'html');
	});

	$('#manuOL').on('click','.manuLI',function(e){ 
		var sel = $(this).html();
		var id = $(this).data('id');
		$.post(nURL+'/solr/sub/index/',{'action':'manClick','man':id,'sfm':sel},function(data){$('#outTest').html(data); uGoNow();},'html'); 
	});
	$('#fClrManu').on('click',function(e){
		$.post(nURL+'/solr/sub/index/',{'action':'manClr'},function(data){$('#outTest').html(data); uGoNow();},'html');
	});

	$('#cataOL').on('click','.cataLI',function(e){
		var sel = $(this).html();
		var id = $(this).data('cid');
		$.post(nURL+'/solr/sub/index/',{'action':'catClick','cat':id,'sfc':sel},function(data){$('#outTest').html(data); uGoNow();},'html');	  
	});
	$('#fClrCata').on('click',function(e){
		$.post(nURL+'/solr/sub/index/',{'action':'catClr'},function(data){$('#outTest').html(data); uGoNow();},'html');
	});

	function uGoNow(){
		location.reload();
		uWaitNow();
		return;
	}
	
	function uWaitNow(){
		$('#waiter').fadeIn('fast');
	}
/*   
 * Keeping examples of addToCar and addToComp //will move later
//add to cart action	
	$('body').on('click','#listLink',function(e){
		var cartUrl = $(this).data('link');
		var cartIt = $.post(cartUrl);
			cartIt.done(function(data){
				location.reload();
			});
	});
		
//compare action
	$('body').on('click','#compIt',function(e){
		var compUrl = $(this).data('link');
		var compIt = $.post(compUrl);
			compIt.done(function(data){
				location.reload();
			});
	});

 *
 **/
});
 </script>
<div id="solrWrap">
<input type="hidden" id="bodySearch" name="qRec" value="" />
	<div id="pSearch"></div>
	<div id="solrBurn"><h3>Search Results</h3><br/></div>
	<div id='outTest'></div>
	<div id='waiter' class='hideMe waitOver'><div class='waitMsg'></div></div>
</div>
<?php else:; ?>
<div>Error.</div>
<?php endif; ?>