<?php
/**
 * Magento
 *
 *
 * @category    code_local_TRU
 * @package     TRU_ProdUp1_SolrBuild
 * @abstract	Use - perform manual updates and purging of the KTS Solr Search Engin.
 * 
 */
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
    <?php echo $this->getChildHtml('head'); ?>
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>
	<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
	<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css">
	<script>$.noConflict();</script>
</head>

<body id="html-body"<?php echo $this->getBodyClass() ? ' class="' . $this->getBodyClass() . '"' : ''; ?>>
<?php echo $this->getChildHtml('notification_window'); ?>
<div class="wrapper">
    <?php echo $this->getChildHtml('global_notices') ?>
        <div class="header">
            <?php echo $this->getChildHtml('header') ?>
        <div class="clear"></div>
            <?php echo $this->getChildHtml('menu') ?>
        </div>
        <?php echo $this->getChildHtml('notifications'); ?>
        <div class="middle" id="anchor-content">
        	
            <div id="page:main-container">
				<div id="sb">
					<div id="ctrCenter"><ul><li><button id="superNova">Clear Existing Index</button></li><li><button id="bigBang">Create New Index</button></li></ul></div>
        			<div id="grpBarHolder" class="grpBarFinder"></div><div id="barHolder" class="barFinder"></div>
				</div>
            </div>
        </div>
        <div class="footer">
            <?php echo $this->getChildHtml('footer') ?>
        </div>
    </div>
    <?php echo $this->getChildHtml('js') ?>
    <?php echo $this->getChildHtml('profiler') ?>
<div id="loading-mask" style="display:none">
    <p class="loader" id="loading_mask_loader"><img src="<?php echo $this->getSkinUrl('images/ajax-loader-tr.gif') ?>" alt="<?php echo Mage::helper('adminhtml')->__('Loading...') ?>"/><br/><?php echo Mage::helper('adminhtml')->__('Please wait...') ?></p>
</div>

<?php echo $this->getChildHtml('before_body_end') ?>
<script>
jQuery(document).ready(function($){
	$('#bigBang').on('click',function(e){
 		var ni = $.post('http://65.60.97.68/index.php/produp1/solrbuild_crawl',{action:'bigBang'});
//		var ni = $.post('http://127.0.0.1/index.php/produp1/solrbuild_crawl',{action:'bigBang'});
		ni.done(function(data){
				$('#grpBarHolder').hide();
				$('#barHolder').html(data).show();
			});
		});
	$('#superNova').on('click',function(e){
		var sn = $.post('http://65.60.97.68/index.php/produp1/solrbuild_crawl',{action:'superNova'});
//		var sn = $.post('http://127.0.0.1/index.php/produp1/solrbuild_crawl',{action:'superNova'});
		sn.done(function(data){
				$('#barHolder').hide();
				$('#grpBarHolder').html(data).show();
			});
	});
});

</script>
</body>
</html>
