<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.0/jquery-ui.min.js"></script>
 <script>
$(function() {
$( "#accordion" ).accordion();
});
</script>
<div class="block block-list">
	<div class="block-title">Filter</div>
	<!-- div class="block-content"> -->
	<div class="accordian">
		<form name="ctFilter">
			<ul>
				<li>
				<strong>Brand</strong>
					<div id="brand" class="filterForm1">
						<input type="checkbox" name="manufacturer" value="osg">&nbsp;OSG<br/>
						<input type="checkbox" name="manufacturer" value="cobra">&nbsp;Cobra Carbide<br/>
						<input type="checkbox" name="manufacturer" value="norseman">&nbsp;Norseman<br/>
						<input type="checkbox" name="manufacturer" value="precision">&nbsp;Precision
					</div></li>
				<li><strong><br/>Material</strong>
					<div id="ctMats" class="filterForm1">
						<input type="checkbox" name="ct_mats" value="High Speed Steel">&nbsp;High Speed Steel (HSS)<br/>
						<input type="checkbox" name="ct_mats" value="High Speed Steel Cobalt">&nbsp;High Speed steel Cobalt (HSSCo)<br/>
						<input type="checkbox" name="ct_mats" value="Carbide">&nbsp;Carbide
					</div></li>
				<li><strong><br/>Length Name</strong>
					<div id="ctLength" class="filterForm1">
						<input type="checkbox" name="ct_length_name" value="Regular">&nbsp;Regular<br/>
						<input type="checkbox" name="ct_length_name" value="Jobber">&nbsp;Jobber<br/>
						<input type="checkbox" name="ct_length_name" value="Stub">&nbsp;Stub<br/>
						<input type="checkbox" name="ct_length_name" value="Extra">&nbsp;Extra<br/>
						<input type="checkbox" name="ct_length_name" value="Mechanic">&nbsp;Mechanic<br/>
						<input type="checkbox" name="ct_length_name" value="Reduced">&nbsp;Reduced<br/>
						<input type="checkbox" name="ct_length_name" value="Screw Machine">&nbsp;Screw Machine<br/>
						<input type="checkbox" name="ct_length_name" value="Taper">&nbsp;Taper<br/>
					</div></li>
				<li><strong><br/>Size Name</strong>
					<div id="ctSzName" class="filterForm1">
							<select name="ct_sz_name" id="ct_sz_name" class="filterFormPull" size="5px" multiple>
								<option value="---">Choose a Drill Size</option>
								<option value="#107">#107 (0.0019 in.) (0.0483 mm)</option>
								<option value="0.05 mm">0.05 mm (0.002 in.) (0.05 mm)</option>
								<option value="#106">#106 (0.0023 in.) (0.0584 mm)</option>
								<option value="#105">#105 (0.0027 in.) (0.0686 mm)</option>
								<option value="#104">#104 (0.0031 in.) (0.0787 mm)</option>
								<option value="#103">#103 (0.0035 in.) (0.0889 mm)</option>
								<option value="#102">#102 (0.0039 in.) (0.0991 mm)</option>
								<option value="0.1 mm">0.1 mm (0.0039 in.) (0.1 mm)</option>
								<option value="#101">#101 (0.0043 in.) (0.1092 mm)</option>
								<option value="#100">#100 (0.0047 in.) (0.1194 mm)</option>
								<option value="#99">#99 (0.0051 in.) (0.1295 mm)</option>
								<option value="#98">#98 (0.0055 in.) (0.1397 mm)</option>
								<option value="#97">#97 (0.0059 in.) (0.1499 mm)</option>
								<option value="#96">#96 (0.0063 in.) (0.16 mm)</option>
								<option value="#95">#95 (0.0067 in.) (0.1702 mm)</option>
								<option value="#94">#94 (0.0071 in.) (0.1803 mm)</option>
								<option value="#93">#93 (0.0075 in.) (0.1905 mm)</option>
								<option value="0.2 mm">0.2 mm (0.0079 in.) (0.2 mm)</option>
								<option value="#92">#92 (0.0079 in.) (0.2007 mm)</option>
								<option value="#91">#91 (0.0083 in.) (0.2108 mm)</option>
								<option value="#90">#90 (0.0087 in.) (0.221 mm)</option>
								<option value="#89">#89 (0.0091 in.) (0.2311 mm)</option>
								<option value="#88">#88 (0.0095 in.) (0.2413 mm)</option>
								<option value="#87">#87 (0.01 in.) (0.254 mm)</option>
								<option value="#86">#86 (0.0105 in.) (0.2667 mm)</option>
								<option value="#85">#85 (0.011 in.) (0.2794 mm)</option>
								<option value="#84">#84 (0.0115 in.) (0.2921 mm)</option>
								<option value="0.3 mm">0.3 mm (0.0118 in.) (0.3 mm)</option>
								<option value="#83">#83 (0.012 in.) (0.3048 mm)</option>
								<option value="#82">#82 (0.0125 in.) (0.3175 mm)</option>
								<option value="#81">#81 (0.013 in.) (0.3302 mm)</option>
								<option value="#80">#80 (0.0135 in.) (0.3429 mm)</option>
								<option value="#79">#79 (0.0145 in.) (0.368 mm)</option>
								<option value="1/64 in">1/64 in (0.0156 in.) (0.3969 mm)</option>
								<option value="0.4 mm">0.4 mm (0.0158 in.) (0.4 mm)</option>
								<option value="#78">#78 (0.016 in.) (0.4064 mm)</option>
								<option value="#77">#77 (0.018 in.) (0.4572 mm)</option>
								<option value="0.5 mm">0.5 mm (0.0197 in.) (0.5 mm)</option>
								<option value="#76">#76 (0.02 in.) (0.508 mm)</option>
								<option value="#75">#75 (0.021 in.) (0.5334 mm)</option>
								<option value="#74">#74 (0.0225 in.) (0.5715 mm)</option>
								<option value="0.6 mm">0.6 mm (0.0236 in.) (0.6 mm)</option>
								<option value="#73">#73 (0.024 in.) (0.6096 mm)</option>
								<option value="#72">#72 (0.025 in.) (0.635 mm)</option>
								<option value="#71">#71 (0.026 in.) (0.6604 mm)</option>
								<option value="0.7 mm">0.7 mm (0.0276 in.) (0.7 mm)</option>
								<option value="#70">#70 (0.028 in.) (0.7112 mm)</option>
								<option value="#69">#69 (0.0292 in.) (0.7417 mm)</option>
								<option value="#68">#68 (0.031 in.) (0.7874 mm)</option>
								<option value="1/32 in">1/32 in (0.0313 in.) (0.7938 mm)</option>
								<option value="0.8 mm">0.8 mm (0.0315 in.) (0.8 mm)</option>
								<option value="#67">#67 (0.032 in.) (0.8128 mm)</option>
								<option value="#66">#66 (0.033 in.) (0.8382 mm)</option>
								<option value="#65">#65 (0.035 in.) (0.889 mm)</option>
								<option value="0.9 mm">0.9 mm (0.0354 in.) (0.9 mm)</option>
								<option value="#64">#64 (0.036 in.) (0.9144 mm)</option>
								<option value="#63">#63 (0.037 in.) (0.9398 mm)</option>
								<option value="#62">#62 (0.038 in.) (0.9652 mm)</option>
								<option value="#61">#61 (0.039 in.) (0.9906 mm)</option>
								<option value="1 mm">1 mm (0.0394 in.) (1 mm)</option>
								<option value="#60">#60 (0.04 in.) (1.016 mm)</option>
								<option value="#59">#59 (0.041 in.) (1.0414 mm)</option>
								<option value="#58">#58 (0.042 in.) (1.0668 mm)</option>
								<option value="#57">#57 (0.043 in.) (1.0922 mm)</option>
								<option value="1.1 mm">1.1 mm (0.0433 in.) (1.1 mm)</option>
								<option value="#56">#56 (0.0465 in.) (1.1811 mm)</option>
								<option value="3/64 in">3/64 in (0.0469 in.) (1.1906 mm)</option>
								<option value="1.2 mm">1.2 mm (0.0472 in.) (1.2 mm)</option>
								<option value="1.3 mm">1.3 mm (0.0512 in.) (1.3 mm)</option>
								<option value="#55">#55 (0.052 in.) (1.3208 mm)</option>
								<option value="#54">#54 (0.055 in.) (1.397 mm)</option>
								<option value="1.4 mm">1.4 mm (0.0551 in.) (1.4 mm)</option>
								<option value="1.5 mm">1.5 mm (0.0591 in.) (1.5 mm)</option>
								<option value="#53">#53 (0.0595 in.) (1.5113 mm)</option>
								<option value="1/16 in">1/16 in (0.0625 in.) (1.5875 mm)</option>
								<option value="1.6 mm">1.6 mm (0.063 in.) (1.6 mm)</option>
								<option value="#52">#52 (0.0635 in.) (1.6129 mm)</option>
								<option value="1.7 mm">1.7 mm (0.0669 in.) (1.7 mm)</option>
								<option value="#51">#51 (0.067 in.) (1.7018 mm)</option>
								<option value="#50">#50 (0.07 in.) (1.778 mm)</option>
								<option value="1.8 mm">1.8 mm (0.0709 in.) (1.8 mm)</option>
								<option value="#49">#49 (0.073 in.) (1.8542 mm)</option>
								<option value="1.9 mm">1.9 mm (0.0748 in.) (1.9 mm)</option>
								<option value="#48">#48 (0.076 in.) (1.9304 mm)</option>
								<option value="5/64 in">5/64 in (0.0781 in.) (1.9844 mm)</option>
								<option value="#47">#47 (0.0785 in.) (1.9939 mm)</option>
								<option value="2 mm">2 mm (0.0787 in.) (2 mm)</option>
								<option value="#46">#46 (0.081 in.) (2.0574 mm)</option>
								<option value="#45">#45 (0.082 in.) (2.0828 mm)</option>
								<option value="2.1 mm">2.1 mm (0.0827 in.) (2.1 mm)</option>
								<option value="#44">#44 (0.086 in.) (2.1844 mm)</option>
								<option value="2.2 mm">2.2 mm (0.0866 in.) (2.2 mm)</option>
								<option value="#43">#43 (0.089 in.) (2.2606 mm)</option>
								<option value="2.3 mm">2.3 mm (0.0906 in.) (2.3 mm)</option>
								<option value="#42">#42 (0.0935 in.) (2.3749 mm)</option>
								<option value="3/32 in">3/32 in (0.0938 in.) (2.3813 mm)</option>
								<option value="2.4 mm">2.4 mm (0.0945 in.) (2.4 mm)</option>
								<option value="#41">#41 (0.096 in.) (2.4384 mm)</option>
								<option value="#40">#40 (0.098 in.) (2.4892 mm)</option>
								<option value="2.5 mm">2.5 mm (0.0984 in.) (2.5 mm)</option>
								<option value="#39">#39 (0.0995 in.) (2.5273 mm)</option>
								<option value="#38">#38 (0.1015 in.) (2.5781 mm)</option>
								<option value="2.6 mm">2.6 mm (0.1024 in.) (2.6 mm)</option>
								<option value="#37">#37 (0.104 in.) (2.6416 mm)</option>
								<option value="2.7 mm">2.7 mm (0.1063 in.) (2.7 mm)</option>
								<option value="#36">#36 (0.1065 in.) (2.7051 mm)</option>
								<option value="7/64 in">7/64 in (0.1094 in.) (2.7781 mm)</option>
								<option value="#35">#35 (0.11 in.) (2.794 mm)</option>
								<option value="2.8 mm">2.8 mm (0.1102 in.) (2.8 mm)</option>
								<option value="#34">#34 (0.111 in.) (2.8194 mm)</option>
								<option value="#33">#33 (0.113 in.) (2.8702 mm)</option>
								<option value="2.9 mm">2.9 mm (0.1142 in.) (2.9 mm)</option>
								<option value="#32">#32 (0.116 in.) (2.9464 mm)</option>
								<option value="3 mm">3 mm (0.1181 in.) (3 mm)</option>
								<option value="#31">#31 (0.12 in.) (3.048 mm)</option>
								<option value="3.1 mm">3.1 mm (0.1221 in.) (3.1 mm)</option>
								<option value="1/8 in">1/8 in (0.125 in.) (3.175 mm)</option>
								<option value="3.2 mm">3.2 mm (0.126 in.) (3.2 mm)</option>
								<option value="#30">#30 (0.1285 in.) (3.2639 mm)</option>
								<option value="3.3 mm">3.3 mm (0.1299 in.) (3.3 mm)</option>
								<option value="3.4 mm">3.4 mm (0.1339 in.) (3.4 mm)</option>
								<option value="#29">#29 (0.136 in.) (3.4544 mm)</option>
								<option value="3.5 mm">3.5 mm (0.1378 in.) (3.5 mm)</option>
								<option value="#28">#28 (0.1405 in.) (3.5687 mm)</option>
								<option value="9/64 in">9/64 in (0.1406 in.) (3.5719 mm)</option>
								<option value="3.6 mm">3.6 mm (0.1417 in.) (3.6 mm)</option>
								<option value="#27">#27 (0.144 in.) (3.6576 mm)</option>
								<option value="3.7 mm">3.7 mm (0.1457 in.) (3.7 mm)</option>
								<option value="#26">#26 (0.147 in.) (3.7338 mm)</option>
								<option value="#25">#25 (0.1495 in.) (3.7973 mm)</option>
								<option value="3.8 mm">3.8 mm (0.1496 in.) (3.8 mm)</option>
								<option value="#24">#24 (0.152 in.) (3.8608 mm)</option>
								<option value="3.9 mm">3.9 mm (0.1535 in.) (3.9 mm)</option>
								<option value="#23">#23 (0.154 in.) (3.9116 mm)</option>
								<option value="5/32 in">5/32 in (0.1563 in.) (3.9688 mm)</option>
								<option value="#22">#22 (0.157 in.) (3.9878 mm)</option>
								<option value="4 mm">4 mm (0.1575 in.) (4 mm)</option>
								<option value="#21">#21 (0.159 in.) (4.0386 mm)</option>
								<option value="#20">#20 (0.161 in.) (4.0894 mm)</option>
								<option value="4.1 mm">4.1 mm (0.1614 in.) (4.1 mm)</option>
								<option value="4.2 mm">4.2 mm (0.1654 in.) (4.2 mm)</option>
								<option value="#19">#19 (0.166 in.) (4.2164 mm)</option>
								<option value="4.3 mm">4.3 mm (0.1693 in.) (4.3 mm)</option>
								<option value="#18">#18 (0.1695 in.) (4.3053 mm)</option>
								<option value="11/64 in">11/64 in (0.1719 in.) (4.3656 mm)</option>
								<option value="#17">#17 (0.173 in.) (4.3942 mm)</option>
								<option value="4.4 mm">4.4 mm (0.1732 in.) (4.4 mm)</option>
								<option value="#16">#16 (0.177 in.) (4.4958 mm)</option>
								<option value="4.5 mm">4.5 mm (0.1772 in.) (4.5 mm)</option>
								<option value="#15">#15 (0.18 in.) (4.572 mm)</option>
								<option value="4.6 mm">4.6 mm (0.1811 in.) (4.6 mm)</option>
								<option value="#14">#14 (0.182 in.) (4.6228 mm)</option>
								<option value="#13">#13 (0.185 in.) (4.699 mm)</option>
								<option value="4.7 mm">4.7 mm (0.185 in.) (4.7 mm)</option>
								<option value="3/16 in">3/16 in (0.1875 in.) (4.7625 mm)</option>
								<option value="4.8 mm">4.8 mm (0.189 in.) (4.8 mm)</option>
								<option value="#12">#12 (0.189 in.) (4.8006 mm)</option>
								<option value="#11">#11 (0.191 in.) (4.8514 mm)</option>
								<option value="4.9 mm">4.9 mm (0.1929 in.) (4.9 mm)</option>
								<option value="#10">#10 (0.1935 in.) (4.9149 mm)</option>
								<option value="#9">#9 (0.196 in.) (4.9784 mm)</option>
								<option value="5 mm">5 mm (0.1969 in.) (5 mm)</option>
								<option value="#8">#8 (0.199 in.) (5.0546 mm)</option>
								<option value="5.1 mm">5.1 mm (0.2008 in.) (5.1 mm)</option>
								<option value="#7">#7 (0.201 in.) (5.1054 mm)</option>
								<option value="13/64 in">13/64 in (0.2031 in.) (5.1594 mm)</option>
								<option value="#6">#6 (0.204 in.) (5.1816 mm)</option>
								<option value="5.2 mm">5.2 mm (0.2047 in.) (5.2 mm)</option>
								<option value="#5">#5 (0.2055 in.) (5.2197 mm)</option>
								<option value="5.3 mm">5.3 mm (0.2087 in.) (5.3 mm)</option>
								<option value="#4">#4 (0.209 in.) (5.3086 mm)</option>
								<option value="5.4 mm">5.4 mm (0.2126 in.) (5.4 mm)</option>
								<option value="#3">#3 (0.213 in.) (5.4102 mm)</option>
								<option value="5.5 mm">5.5 mm (0.2165 in.) (5.5 mm)</option>
								<option value="7/32 in">7/32 in (0.2188 in.) (5.5563 mm)</option>
								<option value="5.6 mm">5.6 mm (0.2205 in.) (5.6 mm)</option>
								<option value="#2">#2 (0.221 in.) (5.6134 mm)</option>
								<option value="5.7 mm">5.7 mm (0.2244 in.) (5.7 mm)</option>
								<option value="#1">#1 (0.228 in.) (5.7912 mm)</option>
								<option value="5.8 mm">5.8 mm (0.2284 in.) (5.8 mm)</option>
								<option value="5.9 mm">5.9 mm (0.2323 in.) (5.9 mm)</option>
								<option value="A">A (0.234 in.) (5.9436 mm)</option>
								<option value="15/64 in">15/64 in (0.2344 in.) (5.9531 mm)</option>
								<option value="6 mm">6 mm (0.2362 in.) (6 mm)</option>
								<option value="B">B (0.238 in.) (6.0452 mm)</option>
								<option value="6.1 mm">6.1 mm (0.2402 in.) (6.1 mm)</option>
								<option value="C">C (0.242 in.) (6.1468 mm)</option>
								<option value="6.2 mm">6.2 mm (0.2441 in.) (6.2 mm)</option>
								<option value="D">D (0.246 in.) (6.2484 mm)</option>
								<option value="6.3 mm">6.3 mm (0.248 in.) (6.3 mm)</option>
								<option value="1/4 in">1/4 in (0.25 in.) (6.35 mm)</option>
								<option value="E">E (0.25 in.) (6.35 mm)</option>
								<option value="6.4 mm">6.4 mm (0.252 in.) (6.4 mm)</option>
								<option value="6.5 mm">6.5 mm (0.2559 in.) (6.5 mm)</option>
								<option value="F">F (0.257 in.) (6.5278 mm)</option>
								<option value="6.6 mm">6.6 mm (0.2598 in.) (6.6 mm)</option>
								<option value="G">G (0.261 in.) (6.6294 mm)</option>
								<option value="6.7 mm">6.7 mm (0.2638 in.) (6.7 mm)</option>
								<option value="17/64 in">17/64 in (0.2656 in.) (6.7469 mm)</option>
								<option value="H">H (0.266 in.) (6.7564 mm)</option>
								<option value="6.8 mm">6.8 mm (0.2677 in.) (6.8 mm)</option>
								<option value="6.9 mm">6.9 mm (0.2717 in.) (6.9 mm)</option>
								<option value="I">I (0.272 in.) (6.9088 mm)</option>
								<option value="7 mm">7 mm (0.2756 in.) (7 mm)</option>
								<option value="J">J (0.277 in.) (7.0358 mm)</option>
								<option value="7.1 mm">7.1 mm (0.2795 in.) (7.1 mm)</option>
								<option value="K">K (0.281 in.) (7.1374 mm)</option>
								<option value="9/32 in">9/32 in (0.2813 in.) (7.1438 mm)</option>
								<option value="7.2 mm">7.2 mm (0.2835 in.) (7.2 mm)</option>
								<option value="7.3 mm">7.3 mm (0.2874 in.) (7.3 mm)</option>
								<option value="L">L (0.29 in.) (7.366 mm)</option>
								<option value="7.4 mm">7.4 mm (0.2913 in.) (7.4 mm)</option>
								<option value="M">M (0.295 in.) (7.493 mm)</option>
								<option value="7.5 mm">7.5 mm (0.2953 in.) (7.5 mm)</option>
								<option value="19/64 in">19/64 in (0.2969 in.) (7.5406 mm)</option>
								<option value="7.6 mm">7.6 mm (0.2992 in.) (7.6 mm)</option>
								<option value="N">N (0.302 in.) (7.6708 mm)</option>
								<option value="7.7 mm">7.7 mm (0.3032 in.) (7.7 mm)</option>
								<option value="7.8 mm">7.8 mm (0.3071 in.) (7.8 mm)</option>
								<option value="7.9 mm">7.9 mm (0.311 in.) (7.9 mm)</option>
								<option value="5/16 in">5/16 in (0.3125 in.) (7.9375 mm)</option>
								<option value="8 mm">8 mm (0.315 in.) (8 mm)</option>
								<option value="O">O (0.316 in.) (8.0264 mm)</option>
								<option value="8.1 mm">8.1 mm (0.3189 in.) (8.1 mm)</option>
								<option value="8.2 mm">8.2 mm (0.3228 in.) (8.2 mm)</option>
								<option value="P">P (0.323 in.) (8.2042 mm)</option>
								<option value="8.3 mm">8.3 mm (0.3268 in.) (8.3 mm)</option>
								<option value="21/64 in">21/64 in (0.3281 in.) (8.3344 mm)</option>
								<option value="8.4 mm">8.4 mm (0.3307 in.) (8.4 mm)</option>
								<option value="Q">Q (0.332 in.) (8.4328 mm)</option>
								<option value="8.5 mm">8.5 mm (0.3347 in.) (8.5 mm)</option>
								<option value="8.6 mm">8.6 mm (0.3386 in.) (8.6 mm)</option>
								<option value="R">R (0.339 in.) (8.6106 mm)</option>
								<option value="8.7 mm">8.7 mm (0.3425 in.) (8.7 mm)</option>
								<option value="11/32 in">11/32 in (0.3438 in.) (8.7313 mm)</option>
								<option value="8.8 mm">8.8 mm (0.3465 in.) (8.8 mm)</option>
								<option value="S">S (0.348 in.) (8.8392 mm)</option>
								<option value="8.9 mm">8.9 mm (0.3504 in.) (8.9 mm)</option>
								<option value="9 mm">9 mm (0.3543 in.) (9 mm)</option>
								<option value="T">T (0.358 in.) (9.0932 mm)</option>
								<option value="9.1 mm">9.1 mm (0.3583 in.) (9.1 mm)</option>
								<option value="23/64 in">23/64 in (0.3594 in.) (9.1281 mm)</option>
								<option value="9.2 mm">9.2 mm (0.3622 in.) (9.2 mm)</option>
								<option value="9.3 mm">9.3 mm (0.3661 in.) (9.3 mm)</option>
								<option value="U">U (0.368 in.) (9.3472 mm)</option>
								<option value="9.4 mm">9.4 mm (0.3701 in.) (9.4 mm)</option>
								<option value="9.5 mm">9.5 mm (0.374 in.) (9.5 mm)</option>
								<option value="3/8 in">3/8 in (0.375 in.) (9.525 mm)</option>
								<option value="V">V (0.377 in.) (9.5758 mm)</option>
								<option value="9.6 mm">9.6 mm (0.378 in.) (9.6 mm)</option>
								<option value="9.7 mm">9.7 mm (0.3819 in.) (9.7 mm)</option>
								<option value="9.8 mm">9.8 mm (0.3858 in.) (9.8 mm)</option>
								<option value="W">W (0.386 in.) (9.8044 mm)</option>
								<option value="9.9 mm">9.9 mm (0.3898 in.) (9.9 mm)</option>
								<option value="25/64 in">25/64 in (0.3906 in.) (9.9219 mm)</option>
								<option value="10 mm">10 mm (0.3937 in.) (10 mm)</option>
								<option value="X">X (0.397 in.) (10.0838 mm)</option>
								<option value="Y">Y (0.404 in.) (10.2616 mm)</option>
								<option value="13/32 in">13/32 in (0.4063 in.) (10.3188 mm)</option>
								<option value="Z">Z (0.413 in.) (10.4902 mm)</option>
								<option value="10.5 mm">10.5 mm (0.4134 in.) (10.5 mm)</option>
								<option value="27/64 in">27/64 in (0.4219 in.) (10.7156 mm)</option>
								<option value="11 mm">11 mm (0.4331 in.) (11 mm)</option>
								<option value="7/16 in">7/16 in (0.4375 in.) (11.1125 mm)</option>
								<option value="11.5 mm">11.5 mm (0.4528 in.) (11.5 mm)</option>
								<option value="29/64 in">29/64 in (0.4531 in.) (11.5094 mm)</option>
								<option value="15/32 in">15/32 in (0.4688 in.) (11.9063 mm)</option>
								<option value="12 mm">12 mm (0.4724 in.) (12 mm)</option>
								<option value="31/64 in">31/64 in (0.4844 in.) (12.3031 mm)</option>
								<option value="12.5 mm">12.5 mm (0.4921 in.) (12.5 mm)</option>
								<option value="1/2 in">1/2 in (0.5 in.) (12.7 mm)</option>
								<option value="13 mm">13 mm (0.5118 in.) (13 mm)</option>
								<option value="33/64 in">33/64 in (0.5156 in.) (13.0969 mm)</option>
								<option value="17/32 in">17/32 in (0.5313 in.) (13.4938 mm)</option>
								<option value="13.5 mm">13.5 mm (0.5315 in.) (13.5 mm)</option>
								<option value="35/64 in">35/64 in (0.5469 in.) (13.8906 mm)</option>
								<option value="14 mm">14 mm (0.5512 in.) (14 mm)</option>
								<option value="9/16 in">9/16 in (0.5625 in.) (14.2875 mm)</option>
								<option value="14.5 mm">14.5 mm (0.5709 in.) (14.5 mm)</option>
								<option value="37/64 in">37/64 in (0.5781 in.) (14.6844 mm)</option>
								<option value="15 mm">15 mm (0.5906 in.) (15 mm)</option>
								<option value="19/32 in">19/32 in (0.5938 in.) (15.0813 mm)</option>
								<option value="39/64 in">39/64 in (0.6094 in.) (15.4781 mm)</option>
								<option value="15.5 mm">15.5 mm (0.6102 in.) (15.5 mm)</option>
								<option value="5/8 in">5/8 in (0.625 in.) (15.875 mm)</option>
								<option value="16 mm">16 mm (0.6299 in.) (16 mm)</option>
								<option value="41/64 in">41/64 in (0.6406 in.) (16.2719 mm)</option>
								<option value="16.5 mm">16.5 mm (0.6496 in.) (16.5 mm)</option>
								<option value="17 mm">17 mm (0.6693 in.) (17 mm)</option>
								<option value="43/64 in">43/64 in (0.6719 in.) (17.0656 mm)</option>
								<option value="11/16 in">11/16 in (0.6875 in.) (17.4625 mm)</option>
								<option value="17.5 mm">17.5 mm (0.689 in.) (17.5 mm)</option>
								<option value="45/64 in">45/64 in (0.7031 in.) (17.8594 mm)</option>
								<option value="18 mm">18 mm (0.7087 in.) (18 mm)</option>
								<option value="23/32 in">23/32 in (0.7188 in.) (18.2563 mm)</option>
								<option value="18.5 mm">18.5 mm (0.7284 in.) (18.5 mm)</option>
								<option value="47/64 in">47/64 in (0.7344 in.) (18.6531 mm)</option>
								<option value="19 mm">19 mm (0.748 in.) (19 mm)</option>
								<option value="3/4 in">3/4 in (0.75 in.) (19.05 mm)</option>
								<option value="49/64 in">49/64 in (0.7656 in.) (19.4469 mm)</option>
								<option value="19.5 mm">19.5 mm (0.7677 in.) (19.5 mm)</option>
								<option value="25/32 in">25/32 in (0.7813 in.) (19.8438 mm)</option>
								<option value="20 mm">20 mm (0.7874 in.) (20 mm)</option>
								<option value="51/64 in">51/64 in (0.7969 in.) (20.2406 mm)</option>
								<option value="20.5 mm">20.5 mm (0.8071 in.) (20.5 mm)</option>
								<option value="13/16 in">13/16 in (0.8125 in.) (20.6375 mm)</option>
								<option value="21 mm">21 mm (0.8268 in.) (21 mm)</option>
								<option value="53/64 in">53/64 in (0.8281 in.) (21.0344 mm)</option>
								<option value="27/32 in">27/32 in (0.8438 in.) (21.4313 mm)</option>
								<option value="21.5 mm">21.5 mm (0.8465 in.) (21.5 mm)</option>
								<option value="55/64 in">55/64 in (0.8594 in.) (21.8281 mm)</option>
								<option value="22 mm">22 mm (0.8661 in.) (22 mm)</option>
								<option value="7/8 in">7/8 in (0.875 in.) (22.225 mm)</option>
								<option value="22.5 mm">22.5 mm (0.8858 in.) (22.5 mm)</option>
								<option value="57/64 in">57/64 in (0.8906 in.) (22.6219 mm)</option>
								<option value="23 mm">23 mm (0.9055 in.) (23 mm)</option>
								<option value="29/32 in">29/32 in (0.9063 in.) (23.0188 mm)</option>
								<option value="21/23 in">21/23 in (0.913 in.) (23.1913 mm)</option>
								<option value="59/64 in">59/64 in (0.9219 in.) (23.4156 mm)</option>
								<option value="23.5 mm">23.5 mm (0.9252 in.) (23.5 mm)</option>
								<option value="15/16 in">15/16 in (0.9375 in.) (23.8125 mm)</option>
								<option value="24 mm">24 mm (0.9449 in.) (24 mm)</option>
								<option value="61/64 in">61/64 in (0.9531 in.) (24.2094 mm)</option>
								<option value="24.5 mm">24.5 mm (0.9646 in.) (24.5 mm)</option>
								<option value="31/32 in">31/32 in (0.9688 in.) (24.6063 mm)</option>
								<option value="25 mm">25 mm (0.9843 in.) (25 mm)</option>
								<option value="63/64 in">63/64 in (0.9844 in.) (25.0031 mm)</option>
								<option value="1 in">1 in (1 in.) (25.4 mm)</option>
								<option value="25.5 mm">25.5 mm (1.0039 in.) (25.5 mm)</option>
								<option value="1 1/64 in">1 1/64 in (1.0156 in.) (25.7969 mm)</option>
								<option value="26 mm">26 mm (1.0236 in.) (26 mm)</option>
								<option value="1 1/32 in">1 1/32 in (1.0313 in.) (26.1938 mm)</option>
								<option value="26.5 mm">26.5 mm (1.0433 in.) (26.5 mm)</option>
								<option value="1 3/64 in">1 3/64 in (1.0469 in.) (26.5906 mm)</option>
								<option value="1 1/16 in">1 1/16 in (1.0625 in.) (26.9875 mm)</option>
								<option value="27 mm">27 mm (1.063 in.) (27 mm)</option>
								<option value="1 5/64 in">1 5/64 in (1.0781 in.) (27.3844 mm)</option>
								<option value="27.5 mm">27.5 mm (1.0827 in.) (27.5 mm)</option>
								<option value="1 3/32 in">1 3/32 in (1.0938 in.) (27.7813 mm)</option>
								<option value="28 mm">28 mm (1.1024 in.) (28 mm)</option>
								<option value="1 7/64 in">1 7/64 in (1.1094 in.) (28.1781 mm)</option>
								<option value="28.5 mm">28.5 mm (1.1221 in.) (28.5 mm)</option>
								<option value="1 1/8 in">1 1/8 in (1.125 in.) (28.575 mm)</option>
								<option value="1 9/64 in">1 9/64 in (1.1406 in.) (28.9719 mm)</option>
								<option value="29 mm">29 mm (1.1417 in.) (29 mm)</option>
								<option value="1 5/32 in">1 5/32 in (1.1563 in.) (29.3688 mm)</option>
								<option value="29.5 mm">29.5 mm (1.1614 in.) (29.5 mm)</option>
								<option value="1 11/64 in">1 11/64 in (1.1719 in.) (29.7656 mm)</option>
								<option value="30 mm">30 mm (1.1811 in.) (30 mm)</option>
								<option value="1 3/16 in">1 3/16 in (1.1875 in.) (30.1625 mm)</option>
								<option value="30.5 mm">30.5 mm (1.2008 in.) (30.5 mm)</option>
								<option value="1 13/64 in">1 13/64 in (1.2031 in.) (30.5594 mm)</option>
								<option value="1 7/32 in">1 7/32 in (1.2188 in.) (30.9563 mm)</option>
								<option value="31 mm">31 mm (1.2205 in.) (31 mm)</option>
								<option value="1 15/64 in">1 15/64 in (1.2344 in.) (31.3531 mm)</option>
								<option value="31.5 mm">31.5 mm (1.2402 in.) (31.5 mm)</option>
								<option value="1 1/4 in">1 1/4 in (1.25 in.) (31.75 mm)</option>
								<option value="32 mm">32 mm (1.2598 in.) (32 mm)</option>
								<option value="1 17/64 in">1 17/64 in (1.2656 in.) (32.1469 mm)</option>
								<option value="32.5 mm">32.5 mm (1.2795 in.) (32.5 mm)</option>
								<option value="1 9/32 in">1 9/32 in (1.2813 in.) (32.5438 mm)</option>
								<option value="1 19/64 in">1 19/64 in (1.2969 in.) (32.9406 mm)</option>
								<option value="33 mm">33 mm (1.2992 in.) (33 mm)</option>
								<option value="1 5/16 in">1 5/16 in (1.3125 in.) (33.3375 mm)</option>
								<option value="33.5 mm">33.5 mm (1.3189 in.) (33.5 mm)</option>
								<option value="1 21/64 in">1 21/64 in (1.3281 in.) (33.7344 mm)</option>
								<option value="34 mm">34 mm (1.3386 in.) (34 mm)</option>
								<option value="1 11/32 in">1 11/32 in (1.3438 in.) (34.1313 mm)</option>
								<option value="34.5 mm">34.5 mm (1.3583 in.) (34.5 mm)</option>
								<option value="1 23/64 in">1 23/64 in (1.3594 in.) (34.5281 mm)</option>
								<option value="1 3/8 in">1 3/8 in (1.375 in.) (34.925 mm)</option>
								<option value="35 mm">35 mm (1.378 in.) (35 mm)</option>
								<option value="1 25/64 in">1 25/64 in (1.3906 in.) (35.3219 mm)</option>
								<option value="35.5 mm">35.5 mm (1.3976 in.) (35.5 mm)</option>
								<option value="1 13/32 in">1 13/32 in (1.4063 in.) (35.7188 mm)</option>
								<option value="36 mm">36 mm (1.4173 in.) (36 mm)</option>
								<option value="1 27/64 in">1 27/64 in (1.4219 in.) (36.1156 mm)</option>
								<option value="36.5 mm">36.5 mm (1.437 in.) (36.5 mm)</option>
								<option value="1 7/16 in">1 7/16 in (1.4375 in.) (36.5125 mm)</option>
								<option value="1 29/64 in">1 29/64 in (1.4531 in.) (36.9094 mm)</option>
								<option value="37 mm">37 mm (1.4567 in.) (37 mm)</option>
								<option value="1 15/32 in">1 15/32 in (1.4688 in.) (37.3063 mm)</option>
								<option value="37.5 mm">37.5 mm (1.4764 in.) (37.5 mm)</option>
								<option value="1 31/64 in">1 31/64 in (1.4844 in.) (37.7031 mm)</option>
								<option value="38 mm">38 mm (1.4961 in.) (38 mm)</option>
								<option value="1 1/2 in">1 1/2 in (1.5 in.) (38.1 mm)</option>	
							</select>
					</div></li>
				<li><strong><br/>Number of Flutes</strong>
					<div id="ct_flute_no" class="filterForm1">
						<input type="checkbox" name="ct_flute_no" value="2">&nbsp;2 Flute<br/>
						<input type="checkbox" name="ct_flute_no" value="3">&nbsp;3 Flute<br/>
						<input type="checkbox" name="ct_flute_no" value="4">&nbsp;4 Flute<br/>
					</div></li>
				<li><strong><br/>Coating</strong>
					<div id="ctCoat" class="filterForm1">
						<input type="checkbox" name="ct_coat" value="Black Oxide">&nbsp;Black Oxide<br/>
						<input type="checkbox" name="ct_coat" value="Titanium Nitride">&nbsp;titanium Nitride(TiN)<br/>
						<input type="checkbox" name="ct_coat" value="Titanium Aluminum Nitride">&nbsp;Titanium Aluminum Nitride (TiAIN)<br/>
						<input type="checkbox" name="ct_coat" value="Titanium Carbon Nitride">&nbsp;Titanium Carbon Nitride (TiCN)<br/>
						<input type="checkbox" name="ct_coat" value="Diamond Powder">&nbsp;Diamond Powder
					</div></li>
			</ul>
		</form>
	</div>
</div>