<?php
/**
 * @category    design
 * @package     default_modern
 * @copyright   Copyright (c) 2011 Magento Inc. (http://www.magentocommerce.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<div class="footer-container">
    <div class="footer">
        <?php echo $this->getChildHtml('bottomContainer') ?>
        <div class="f-right">
            
            <?php echo $this->getChildHtml('store_switcher') ?>
        </div>
        <div class="f-left">
            <?php echo $this->getChildHtml('cms_footer_links') ?>
            <?php echo $this->getChildHtml('footer_links') ?>
            <div id="newsletter"><?php echo $this->getChildHtml('newsletter') ?></div>
            <address><?php echo $this->getCopyright() ?></address>
        </div>
    </div>
</div>
