<?php
/**
 * Category layered navigation
 *
 * @see Mage_Catalog_Block_Layer_View
 */
?>
<?php 
	if($_GET['qRec']){
		$_filters=array('Category','Price','Manufacturer');
		$html1 = '	<div id="leftFilter" class="block block-layered-nav">
						<div class="block-title">
							<strong><span>Shop By</span></strong>
						</div>
						<div class="block-content">
						<p id="filterTitle" class="block-subtitle">Shopping Options</p>
						<dl id="narrow-by-list">';
		echo($html1);
// filter test for speed improvement
//
		$session = Mage::getSingleton('core/session', array('name'=>'frontend'));
		$collection = Mage::getResourceModel('catalog/product_collection')
//		->addAttributeToSelect('price','manufacturer','category_ids')
		->addAttributeToSelect('*')
		->addIdFilter($session->getData('aFilt'));
		
		foreach ($collection as $prodp){
			//Price Information//
			$_price=$prodp->getPrice();
			if(array_key_exists($_price,$priceArr)){
				$priceArr[$_price]++;
			}else{
				$priceArr[$_price]=1;
			}
			$priceInfo=$priceArr;
		}
		// price structure
		ksort($priceInfo);
		$priceTempArr=array_sum(array_keys($priceInfo));
		$priceAvg=$priceTempArr/count($priceInfo);
		$pv=array_keys($priceInfo);
		foreach($pv as $nv){
			$n=intval($nv);
			if($n>999){
				$priceSetArr["$1000.00 or more"][]=$n;
			}elseif($n>=500){
				$priceSetArr["$500.00 to $999.99"][]=$n;
			}elseif($n>=200){
				$priceSetArr["$200.00 to $499.99"][]=$n;
			}elseif($n>=100){
				$priceSetArr["$100.00 to $199.99"][]=$n;
			}elseif($n>=50){
				$priceSetArr["$50.00 to $99.99"][]=$n;
			}elseif($n>=10){
				$priceSetArr["$10.00 to $49.99"][]=$n;
			}elseif($n>=1){
				$priceSetArr["$1.00 to $9.99"][]=$n;
			}else{
				$priceSetArr["$0 to $.99"][]=$n;
			}
		}
		
		$pFilt=trim($session->getData('solrFilter-price'));
		$priceOut='<dt>Price</dt><dd><ol id="priceOL">';
		foreach($priceSetArr as $psa1=>$psa1a){
			$psa1Fix=str_getcsv($psa1,'(');
			if($psa1 == $pFilt){
				$priceOut.= '<li class="priceLI liTouch">'.$psa1.' </li>';
			}else{
				$priceOut.='<li class="priceLI liStart">'.$psa1.' </li>';//('.count($psa1a).')
			}
		}   $priceOut.= '</ol><div id="fClrPrice" class="fClr">Reset</div></dd>';
		
		// cat information
		foreach ($collection as $prodc){
			$_cid=$prodc->getCategoryIds();
			foreach($_cid as $_catID){
				$_cat = Mage::getSingleton('catalog/category')->load($_catID);
				$_catInfo=$_catID;
				$cataInfo[$_catID]=$_cat->getName();
			}
		}
		$pFilt=trim($session->getData('solrFilter-cat'));
		$cataOut='<dt>Category</dt><dd><ol id="cataOL">';
		foreach($cataInfo as $ci=>$ciCt){
			if($pFilt == $ciCt){
				$cataOut=$cataOut.'<li class="cataLI liTouch" data-cId="'.$ci.'">'.$ciCt.'</li>';
			}else{
				$cataOut=$cataOut.'<li class="cataLI liStart" data-cId="'.$ci.'">'.$ciCt.'</li>';
			}
		}
		$cataOut=$cataOut.'</ol><div id="fClrCata" class="fClr">Reset</div></dd>';
		
		// man information
		foreach ($collection as $prodm){
			$mid=$prodm->getManufacturer();
			$mnm=$prodm->getAttributeText('manufacturer');
			$manuInfo[$mid]=$mnm;
		}
		$pFilt=trim($session->getData('solrFilter-man'));
		$manuOut='<dt>Manufacturer</dt><dd><ol id="manuOL">';
		foreach($manuInfo as $mi=>$miCt){
			if($pFilt == $miCt){
				$manuOut=$manuOut.'<li class="manuLI liTouch" data-id="'.$mi.'">'.$miCt.'</li>';
			}else{
				$manuOut=$manuOut.'<li class="manuLI liStart" data-id="'.$mi.'">'.$miCt.'</li>';
			}
		}
		$manuOut=$manuOut.'</ol><div id="fClrManu" class="fClr">Reset</div></dd>';
		
		echo($priceOut.$cataOut.$manuOut);		
		
//		foreach($_filters as $filter){
//			echo('		<dt>'.$filter.'</dt><dd id="id'.$filter.'">No Filter Information Found</dd>');
//		}
		echo('	</dl></div>');
		$html2 = '	<div id="deepSearch" class="block-content">
						<p id="deepSearchTitle" class="block-subtitle"></p>
						<dl id="deepList">
							<dt id="deepTitle">Popular Search Terms</dt>
							<dd id="deepRes" class="dr1" style="display:block;">
								<ol class="ol1">
									<li></li>
								</ol>
							</dd>
						</dl>
					</div>
				</div>
		';
	echo($html2);
	}else{
		// orig file info
		if($this->canShowBlock()){
			echo('<div id="leftFilter" class="block block-layered-nav">');
			echo('	<div class="block-title">');
			echo('		<strong><span>Shop By</span></strong>');
			echo('	</div>');
			echo('	<div class="block-content">');
			echo('		'.$this->getStateHtml());
        	if($this->getLayer()->getState()->getFilters()){
				echo('<div class="actions"><a href="'.$this->getClearUrl().'">'.$this->__('Clear All').'</a></div>');
			}
        	if($this->canShowOptions()){
				echo('<p id="filterTitle" class="block-subtitle">Shopping Options</p>');
				echo('<dl id="narrow-by-list">');
            	$_filters = $this->getFilters();
				foreach ($_filters as $_filter){
					if($_filter->getItemsCount()){
						echo('<dt>'.$this->__($_filter->getName()).'</dt>');
						echo('<dd id="id'.$this->__($_filter->getName()).'">'.$_filter->getHtml().'</dd>');
					}
                }
            	echo('</dl>');
            	echo('<script type="text/javascript">decorateDataList("narrow-by-list")</script>');
        	}
			echo('</div>');
		}
	}
?>