<?php
/**
 * Magento
 *
 * Another Magento Page Destroyed by Eric ;)
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2012 Magento Inc. (http://www.magentocommerce.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php
/**
 * Category layered navigation
 *
 * @see Mage_Catalog_Block_Layer_View
 */
?>
<?php
//tmp design pattern
//<dt class="code" id="code">Name</dt>
//	<dd id="code">
//		<ol><li id="code" data-code="code" data-val="val">val</li></ol>
//	</dd>

$session=Mage::getSingleton('core/session', array('name'=>'frontend'));

$thisPage=$this->getRequest()->getParams()['id'];

function pgCol($thisPage){
	$cataCol=Mage::getModel('catalog/category')
	->load($thisPage) //$thisPage
	->getProductcollection();
	foreach($cataCol as $cc){
		$pList[]=$cc->getId();
	}
	return $pList; //prod id's for category
}

$ctFilt = $session->getData('ctFilt');
if(count($ctFilt<0)){
	$ctFilt = array_pad($ctFilt, 1, "~:~");
}


if(count(pgCol($thisPage))>0){
	$fJSON=json_decode(Mage::helper('gfilter')->getFilterData(pgCol($thisPage)));

	$jOut="";
	foreach($fJSON as $fj1=>$fj2){
		foreach($fj2 as $fj3=>$fj4){
			$cfct=0;
			foreach($ctFilt as $tf){
				$tf1 = str_getcsv($tf,':')[0];
				if($fj1 == $tf1){
					$jOut.='<dt class="'.$fj1.'" id="'.$fj1.'">'.$fj3.'<div id="selPar"></div></dt><dd id="'.$fj1.'"><ol>';
					$cfct++;
				}
			}
			if($cfct==0){
			$jOut.='<dt class="'.$fj1.'" id="'.$fj1.'">'.$fj3.'</dt><dd id="'.$fj1.'"><ol>';
			}
			
		}
			$vals=str_getcsv($fj4,',');
			foreach($vals as $val){
				$cfct1=0;
				foreach($ctFilt as $cf){
					$cf1 = str_getcsv($cf,':')[1];
					if(rtrim($val,'"') == rtrim($cf1,'"')){
						$jOut.='<li id="'.$fj1.'" data-code="'.$fj1.'" data-val="'.$val.'" class="liTouch">'.$val.'<div id="selLi"></div></li>';
						$cfct1++;
					}
				}
				if($cfct1==0){
					$jOut.='<li id="'.$fj1.'" data-code="'.$fj1.'" data-val="'.$val.'" class="liStart">'.$val.'</li>';
				}
			}
			$jOut.='</ol></dd>';
		}
	
	$filterBase='<div id="leftFilter" class="block block-layered-nav">
		<div class="block-title">
			<strong><span>Shop By</span></strong>
		</div>
		<p id="filterTitle" class="block-subtitle">Shopping Options</p>		
		<dl id="narrow-by-list">'.$jOut.'
		</dl>
 		<!--<div id="filterCtl">
 			<div id="filterList"><p></p><ul></ul></div>
 		</div>-->
		
	</div>';
print_r($filterBase);

?>
<script type="text/javascript">
<!--
jQuery('#narrow-by-list').accordion({
	collapsible:true,
	active:false,
	heightStyle:"content"
});
//-->
</script>
<?php 

}else{
if($this->canShowBlock()): ?>
echo('fire');
<div id="leftFilter" class="block block-layered-nav">
    <div class="block-title">
        <strong><span><?php echo $this->__('Shop By') ?></span></strong>
    </div>
    <div class="block-content">
        <?php echo $this->getStateHtml() ?>
        <?php if ($this->getLayer()->getState()->getFilters()): ?>
            <div class="actions"><a href="<?php echo $this->getClearUrl() ?>"><?php echo $this->__('Clear All') ?></a></div>
        <?php endif; ?>
        <?php if($this->canShowOptions()): ?>
            <p id="filterTitle" class="block-subtitle"><?php echo $this->__('Shopping Options111') ?></p>
            <dl id="narrow-by-list">
                <?php $_filters = $this->getFilters() ?>
                <?php foreach ($_filters as $_filter): ?>
                <?php if($_filter->getItemsCount()): ?>
                    <dt><?php echo $this->__($_filter->getName()) ?></dt>
                    <dd id=id<?php echo $this->__($_filter->getName())?>><?php echo $_filter->getHtml() ?></dd>
                <?php endif; ?>
                <?php endforeach; ?>
            </dl>
            <script type="text/javascript">decorateDataList('narrow-by-list')</script>
        <?php endif; ?>		
	</div>
	<?php if($_GET['qRec']):?>
	<div id="deepSearch" class="block-content">
		<p id='deepSearchTitle' class="block-subtitle"></p>
		<dl id="deepList">
			<dt id="deepTitle">Popular Search Terms</dt>
			<dd id="deepRes" class="dr1" style="display:block;">
				<ol class="ol1">
					<li></li>
				</ol>
			</dd>
		</dl>
	</div>
		<?php endif; ?>      
</div>
<?php endif; 
if($_GET['qRec']){
?>
<script type="text/javascript">
<!--
	//hide data for search lol
	jQuery('#idCategory').hide();
	jQuery('#idPrice').hide();
	jQuery('#idManufacturer').hide();
//-->
</script>
<?php 
}
}
?>
